version: '2'

services:
  web:
    container_name: bingo
    build: .
    image: bingo
    command: elm-reactor --address=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - .:/usr/src/app/elm-stuff
